version: "3.9"

services:

  creator-node:
    build: creator-node
    command: sh -c "tail -f /dev/null"
    env_file: .env # used by the startup script
    volumes:
      # Mount the root folder that contains .git
      #- .:/workspace:cached
      - ./creator-node/src:/usr/src/app/src

  discovery-provider:
    build: discovery-provider
    command: sh -c "tail -f /dev/null"
    env_file: .env # used by the startup script
    volumes:
      # Mount the root folder that contains .git
      #- .:/workspace:cached
      - ./discovery-provider/src:/audius-discovery-provider/src

  identity-service:
    build: identity-service
    command: sh -c "tail -f /dev/null"
    env_file: .env # used by the startup script
    volumes:
      # Mount the root folder that contains .git
      # - .:/workspace:cached
      - ./identity-service/src:/usr/src/app/src
