  ###########
  # local.yml
  ###########

  #############################################
  # monitor custom exporters produced by audius
  #############################################

  # monitor data growth using containers running colocated on prometheus-grafana-metrics

  - job_name: 'census-local'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'audius'
          component: 'monitoring'
          job: 'census'

  ###################################################
  # monitor local (remote-dev) setups that use docker
  ###################################################

  # monitor discovery provider containers

  - job_name: 'local-discovery-provider'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'audius'
          component: 'discovery-provider'

  # monitor content node containers

  - job_name: 'local-content-node-1'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4000']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'audius'
          component: 'content-node'

  - job_name: 'local-content-node-2'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4001']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'audius'
          component: 'content-node'

  - job_name: 'local-content-node-3'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4002']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'audius'
          component: 'content-node'

  - job_name: 'local-content-node-4'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4003']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'audius'
          component: 'content-node'
