  ###########
  # stage.yml
  ###########

  #############################################
  # monitor custom exporters produced by audius
  #############################################

  # monitor data growth using containers running colocated on prometheus-grafana-metrics

  - job_name: 'census-stage'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          host: 'host.docker.internal'
          environment: 'stage'
          service: 'audius'
          component: 'monitoring'
          job: 'census'
