version: '3'
services:
  comdb:
    container_name: comdb
    image: postgres
    restart: unless-stopped
    ports:
      - 5454:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./discovery/db/docker-initdb:/docker-entrypoint-initdb.d

  com1:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: com1
    restart: unless-stopped
    environment:
      audius_discprov_env: test
      test_host: com1
      storage_v2: "true"
      audius_delegate_owner_wallet: "0x1c185053c2259f72fd023ED89B9b3EBbD841DA0F"
      audius_delegate_private_key: "293589cdf207ed2f2253bb72b17bb7f2cfe399cdc34712b1d32908d969682238"
      audius_db_url: "postgresql://postgres:postgres@comdb:5432/com1?sslmode=disable"
      audius_comms_cluster: "true"
    command:
      - nats
    depends_on:
      - comdb
    stop_signal: SIGKILL
    ports:
      - 8924:8924
    volumes:
      - com1:/tmp/nats

  storage1:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: storage1
    restart: unless-stopped
    environment:
      NAME: storage1
      test_host: storage1
      storage_v2: "true"
      audius_delegate_owner_wallet: "0x1c185053c2259f72fd023ED89B9b3EBbD841DA0F"
      audius_delegate_private_key: "293589cdf207ed2f2253bb72b17bb7f2cfe399cdc34712b1d32908d969682238"
    command:
      - storage
    depends_on:
      - com1
    stop_signal: SIGKILL
    ports:
      - 9924:8926

  com2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: com2
    restart: unless-stopped
    environment:
      audius_discprov_env: test
      test_host: com2
      storage_v2: "true"
      audius_delegate_owner_wallet: "0x90b8d2655A7C268d0fA31758A714e583AE54489D"
      audius_delegate_private_key: "1ca1082d2304d96c2e6a3e551226e72e2cb54fddfe69b946b0efc2d9b43c19fc"
      audius_db_url: "postgresql://postgres:postgres@comdb:5432/com2?sslmode=disable"
      audius_comms_cluster: "true"
    command:
      - nats
    depends_on:
      - comdb
    stop_signal: SIGKILL
    ports:
      - 8925:8924
    volumes:
      - com2:/tmp/nats

  storage2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: storage2
    restart: unless-stopped
    environment:
      NAME: storage2
      test_host: storage2
      storage_v2: "true"
      audius_delegate_owner_wallet: "0x90b8d2655A7C268d0fA31758A714e583AE54489D"
      audius_delegate_private_key: "1ca1082d2304d96c2e6a3e551226e72e2cb54fddfe69b946b0efc2d9b43c19fc"
    command:
      - storage
    depends_on:
      - com2
    stop_signal: SIGKILL
    ports:
      - 9925:8926

  com3:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: com3
    restart: unless-stopped
    environment:
      audius_discprov_env: test
      test_host: com3
      storage_v2: "true"
      audius_delegate_owner_wallet: "0xb7b9599EeB2FD9237C94cFf02d74368Bb2df959B"
      audius_delegate_private_key: "12712efcf90774399e272f8fc89ef264058b4cdd7f7f86956052050cbfb4350c"
      audius_db_url: "postgresql://postgres:postgres@comdb:5432/com3?sslmode=disable"
      audius_comms_cluster: "true"
    command:
      - nats
    depends_on:
      - comdb
    stop_signal: SIGKILL
    ports:
      - 8926:8924
    volumes:
      - com3:/tmp/nats

  storage3:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: storage3
    restart: unless-stopped
    environment:
      NAME: storage3
      test_host: storage3
      storage_v2: "true"
      audius_delegate_owner_wallet: "0xb7b9599EeB2FD9237C94cFf02d74368Bb2df959B"
      audius_delegate_private_key: "12712efcf90774399e272f8fc89ef264058b4cdd7f7f86956052050cbfb4350c"
    command:
      - storage
    depends_on:
      - com3
    stop_signal: SIGKILL
    ports:
      - 9926:8926

  com4:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: com4
    restart: unless-stopped
    environment:
      audius_discprov_env: test
      test_host: com4
      storage_v2: "true"
      audius_delegate_owner_wallet: "0xfa4f42633Cb0c72Aa35D3D1A3566abb7142c7b16"
      audius_delegate_private_key: "2617e6258025c60b5aa270e02ff2247eefab37c7b463b2a870104862870ad3fb"
      audius_db_url: "postgresql://postgres:postgres@comdb:5432/com4?sslmode=disable"
      audius_comms_cluster: "true"
    command:
      - nats
    depends_on:
      - comdb
    stop_signal: SIGKILL
    ports:
      - 8927:8924
    volumes:
      - com4:/tmp/nats

  storage4:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: "comms:v2"
    container_name: storage4
    restart: unless-stopped
    environment:
      NAME: storage4
      test_host: storage4
      storage_v2: "true"
      audius_delegate_owner_wallet: "0xfa4f42633Cb0c72Aa35D3D1A3566abb7142c7b16"
      audius_delegate_private_key: "2617e6258025c60b5aa270e02ff2247eefab37c7b463b2a870104862870ad3fb"
    command:
      - storage
    depends_on:
      - com4
    stop_signal: SIGKILL
    ports:
      - 9927:8926

volumes:
  com1:
  com2:
  com3:
  com4:
